# Generated by Django 3.2.16 on 2023-03-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='excercisesdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=500)),
                ('weight', models.CharField(max_length=300)),
                ('excercise1', models.CharField(max_length=300)),
                ('excercise2', models.CharField(max_length=300)),
                ('diet', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(upload_to='files/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='userregistrationmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('loginid', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('height', models.FloatField()),
                ('weight', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=100)),
                ('authkey', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dailystatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('excercise', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.FloatField(max_length=100)),
                ('date', models.DateField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('caloriesburned', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('name', 'date')},
            },
        ),
    ]
